server {
  listen 80;
  server_name _;

  location = /ofertawhats {
    return 301 /ofertawhats/;
  }

  location /ofertawhats/ {
    alias /usr/share/nginx/html/;
    try_files $uri $uri/ /ofertawhats/index.html;
  }
}
